title: !secret home_name

resources:
  - url: https://fonts.googleapis.com/css?family=Comfortaa&display=swap
    type: css
  - url: /local/ui_components/mini-media-player-bundle.js
    type: module

views:

# ------------------------------------------------------------ #
#                       Heima View                             #
# ------------------------------------------------------------ #
  - id: 0
    icon: mdi:home
    name: Heima
    cards:
      - type: vertical-stack
        cards:
          # -------------------------------------------------- #
          #              Weather View                          #
          # -------------------------------------------------- #
          - type: weather-forecast
            entity: weather.husvaetti

          # -------------------------------------------------- #
          #              Calendar View                         #
          # -------------------------------------------------- #
          - type: calendar
            entities:
              - !secret private_calendar_mapping_0_ui
              - !secret private_calendar_mapping_1_ui
              - !secret private_calendar_mapping_2_ui
              - !secret work_calendar_mapping_0_ui

      # ------------------------------------------------------ #
      #                 Media Player View                      #
      # ------------------------------------------------------ #
      - type: custom:mini-media-player
        entity: media_player.frigg
        hide:
          volume: true

      # ------------------------------------------------------ #
      #                 Map View                               #
      # ------------------------------------------------------ #
      - type: map
        aspect_ratio: 16:9
        default_zoom: 12
        entities:
          - zone.home

# ------------------------------------------------------------ #
#                       Work Systems View                      #
# ------------------------------------------------------------ #
  - id: work-systems
    icon: mdi:server
    name: Fjakkarin
    cards:
      - type: horizontal-stack
        title: Remote systems
        cards:
          - type: entities
            title: Linode
            entities:
              - entity: !secret linode_sever_0_ui
                icon: mdi:server
              - entity: !secret linode_sever_1_ui
                icon: mdi:server
              - entity: !secret linode_sever_2_ui
                icon: mdi:server