title: !secret home_name

resources:
  - url: https://fonts.googleapis.com/css?family=Comfortaa&display=swap
    type: css
  - url: /local/ui_components/mini-media-player-bundle.js
    type: module

views:

# ------------------------------------------------------------ #
#                       Heima View                             #
# ------------------------------------------------------------ #
  - id: 0
    icon: mdi:home
    name: Heima
    cards:
      - type: vertical-stack
        cards:
          # -------------------------------------------------- #
          #              Weather View                          #
          # -------------------------------------------------- #
          - type: weather-forecast
            entity: weather.husvaetti

          # -------------------------------------------------- #
          #              Calendar View                         #
          # -------------------------------------------------- #
          - type: calendar
            entities:
              - !secret private_calendar_mapping_0_ui
              - !secret private_calendar_mapping_1_ui
              - !secret private_calendar_mapping_2_ui
              - !secret work_calendar_mapping_0_ui

      # ------------------------------------------------------ #
      #                 Media Player View                      #
      # ------------------------------------------------------ #
      - type: custom:mini-media-player
        entity: media_player.frigg
        hide:
          volume: true

      # ------------------------------------------------------ #
      #                 Map View                               #
      # ------------------------------------------------------ #
      - type: map
        aspect_ratio: 16:9
        default_zoom: 12
        entities:
          - zone.home

# ------------------------------------------------------------ #
#                       Work Systems View                      #
# ------------------------------------------------------------ #
  - id: work-systems
    icon: mdi:server
    title: Fjakkarin
    cards:
      - type: entities
        title: !secret linode_server_0
        show_header_toggle: false
        entities:
          - type: attribute
            entity: !secret linode_server_0_ui
            name: Created
            icon: mdi:timer
            state_color: true
            format: relative
            attribute: created
          - type: attribute
            entity: !secret linode_server_0_ui
            name: IP (v4)
            icon: mdi:switch
            state_color: true
            attribute: ipv4_address
          - type: attribute
            entity: !secret linode_server_0_ui
            name: IP (v6)
            icon: mdi:switch
            state_color: true
            attribute: ipv6_address
          - type: attribute
            entity: !secret linode_server_0_ui
            name: Mem
            icon: mdi:harddisk
            state_color: true
            suffix: GB
            attribute: memory
          - type: attribute
            entity: !secret linode_server_0_ui
            name: Location
            icon: mdi:earth
            state_color: true
            attribute: region
          - type: attribute
            entity: !secret linode_server_0_ui
            name: Running
            icon: mdi:server
            state_color: true
            attribute: device_class
      - type: entities
        title: !secret linode_server_1
        show_header_toggle: false
        entities:
          - type: attribute
            entity: !secret linode_server_1_ui
            name: Created
            icon: mdi:timer
            state_color: true
            format: relative
            attribute: created
          - type: attribute
            entity: !secret linode_server_1_ui
            name: IP (v4)
            icon: mdi:switch
            state_color: true
            attribute: ipv4_address
          - type: attribute
            entity: !secret linode_server_1_ui
            name: IP (v6)
            icon: mdi:switch
            state_color: true
            attribute: ipv6_address
          - type: attribute
            entity: !secret linode_server_1_ui
            name: Mem
            icon: mdi:harddisk
            state_color: true
            suffix: GB
            attribute: memory
          - type: attribute
            entity: !secret linode_server_1_ui
            name: Location
            icon: mdi:earth
            state_color: true
            attribute: region
          - type: attribute
            entity: !secret linode_server_1_ui
            name: Running
            icon: mdi:server
            state_color: true
            attribute: device_class
      - type: entities
        title: !secret linode_server_2
        show_header_toggle: false
        entities:
          - type: attribute
            entity: !secret linode_server_2_ui
            name: Created
            icon: mdi:timer
            state_color: true
            format: relative
            attribute: created
          - type: attribute
            entity: !secret linode_server_2_ui
            name: IP (v4)
            icon: mdi:switch
            state_color: true
            attribute: ipv4_address
          - type: attribute
            entity: !secret linode_server_2_ui
            name: IP (v6)
            icon: mdi:switch
            state_color: true
            attribute: ipv6_address
          - type: attribute
            entity: !secret linode_server_2_ui
            name: Mem
            icon: mdi:harddisk
            state_color: true
            suffix: GB
            attribute: memory
          - type: attribute
            entity: !secret linode_server_2_ui
            name: Location
            icon: mdi:earth
            state_color: true
            attribute: region
          - type: attribute
            entity: !secret linode_server_2_ui
            name: Running
            icon: mdi:server
            state_color: true
            attribute: device_class